M48
; DRILL file {KiCad 9.0.0-9.0.0-2~ubuntu24.04.1} date 2025-04-10T13:45:37-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-10T13:45:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-9.0.0-2~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.9836Y-4.8409
X6.0236Y-5.0409
X6.0636Y-4.8409
T2
X7.4409Y-4.8819
M30
