%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/daniel/GitHub/ECE2799_LED-Lamp/Simulation/LT3799-1_DC1816A.txt
%
% Auto-generated by MATLAB on 15-Apr-2025 07:41:05

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "V_out_", "V_n023_", "I_D5_", "I_L4_"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
LT3799_1_DC1816A = readtable("/home/daniel/GitHub/ECE2799_LED-Lamp/Simulation/LT3799-1_DC1816A.txt", opts);


%% Clear temporary variables
clear opts